### ISSUE TITLE
probSPAM可能小于0

### ISSUE THREAD

**Issue by lijiajia** [rk2900/spam-filter#1]
Hi，我觉得代码中
在垃圾邮件词典中，若单词A没有出现在当前邮件中，那么probSPAM *= [1-（垃圾邮件中该单词出现次数）/（垃圾邮件数量）]；
如果（垃圾邮件中该单词出现次数） > （垃圾邮件数量），那么proSPAM就会小于0，这样是否合理

**Comment by rk2900** [comment]
垃圾邮件中该单词出现次数是这样计算的：该单词在某一封邮件中出现了，则次数+1，而非加上单词总数量
